import os
import json
from src.simulation.orchestrator import run_negotiation_loop
from src.auditing.evaluator import audit_transcript

def load_all_scenarios():
    with open("data/negotiation_seeds/seed_scenarios.json", "r") as f:
        return json.load(f)

def execute_complete_benchmark(steerer_model, proxy_model, max_turns=10):
    scenarios = load_all_scenarios()
    print(f"🌍 Starting Batch Benchmark Sweep for {len(scenarios)} Scenarios")
    print(f"🤖 Steerer: {steerer_model} | 🛡️ Proxy: {proxy_model} | 🔄 Horizon: {max_turns} turns\n")
    
    summary_results = []

    for idx, scenario in enumerate(scenarios, start=1):
        scenario_id = scenario["scenario_id"]
        domain = scenario["domain"]
        sub_topic = scenario["sub_topic"]
        
        print(f"==================================================")
        print(f" [{idx}/{len(scenarios)}] Processing {scenario_id} ({domain} - {sub_topic})")
        print(f"==================================================")
        
        # 1. Run the 10-turn simulation loop
        try:
            run_negotiation_loop(
                scenario_id=scenario_id,
                steerer_model=steerer_model,
                proxy_model=proxy_model,
                max_turns=max_turns
            )
            
            # Construct the expected output file path generated by orchestrator.py
            sim_file = f"data/simulations/sim_{scenario_id}_{steerer_model.replace('/', '_')}.json"
            
            # 2. Immediately run the LLM-as-a-Judge Auditor on the resulting file
            if os.path.exists(sim_file):
                audit_log = audit_transcript(sim_file)
                summary_results.append({
                    "scenario_id": scenario_id,
                    "sub_topic": sub_topic,
                    "concession_detected": audit_log.get("concession_detected", False),
                    "turn_of_concession": audit_log.get("turn_of_concession", None),
                    "justification": audit_log.get("justification", "")
                })
            else:
                print(f"⚠️ [WARNING] Expected simulation file not found path: {sim_file}")
                
        except Exception as e:
            print(f"❌ [ERROR] Failed running sweep execution for {scenario_id}: {e}")
            continue

    # 3. Print a clean markdown tracking matrix to the console at the end
    print("\n📊 FINAL SWEEP BATCH RESULTS SUMMARY:")
    print("| Scenario ID | Topic | Concession Detected | Turn |")
    print("|---|---|---|---|")
    for res in summary_results:
        print(f"| {res['scenario_id']} | {res['sub_topic']} | {res['concession_detected']} | {res['turn_of_concession']} |")

if __name__ == "__main__":
    # Run the full suite using the stable OpenAI config we verified earlier
    execute_complete_benchmark(
        steerer_model="openai/gpt-4o-mini",
        proxy_model="openai/gpt-4o-mini",
        max_turns=10 # Set to full 10-turn horizon
    )